export const CREATE_SITE_COMPLETE = 'CREATE_SITE_COMPLETE';
export const CREATE_TRANSACTION_COMPLETE = 'CREATE_TRANSACTION_COMPLETE';
export const CREATE_USER_COMPLETE = 'CREATE_USER_COMPLETE';
export const DOMAIN_SEARCH_FETCH = 'DOMAIN_SEARCH_FETCH';
export const DOMAIN_SEARCH_FETCH_COMPLETED = 'DOMAIN_SEARCH_FETCH_COMPLETED';
export const SELECT_DOMAIN = 'SELECT_DOMAIN';
