export const CREATE_SITE_COMPLETE = 'CREATE_SITE_COMPLETE';
export const CREATE_TRANSACTION_COMPLETE = 'CREATE_TRANSACTION_COMPLETE';
export const CREATE_USER_COMPLETE = 'CREATE_USER_COMPLETE';
export const SELECT_DOMAIN = 'SELECT_DOMAIN';